---
title: "Synergies in Learning Form and Meaning"
author: "Fourtassi & Dupoux"
date: "May 4, 2016"
output:
  html_document:
    number_sections: yes
    toc: yes
---

Libraries.

```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(readr)
library(ggplot2)
library(langcog)
library(boot)
library(lme4)
library(lazyeval)
theme_set(theme_bw())

```

Data. 

```{r}
d <- read_delim("data.txt", delim = "\t") %>%
  filter(item != "filler")

#number of participants
demo <- d %>%
  group_by(ID)%>%
  summarise(freq=n())%>%
  mutate(twice=ifelse(freq > 16, TRUE, FALSE))%>%
  select(-freq)

d_no_twice <- d %>%
  left_join(demo) %>%
  filter(!twice) 

d_score <- d_no_twice %>%
  filter (score > 0.5) 

d_quality <- d_score %>%
  filter (quality=="good") %>%
  group_by(ID)%>%
  summarise(freq=n())%>%
  nrow()


```

Data summary

```{r}

data <- d_quality %>%
  rename(type=test, trial=ident, group=condition)

```

Hits and False Alarms
```{r}

av_after <- data %>%
  filter(session==1) %>%
  group_by(group, trial) %>%
  multi_boot_standard(col = "res")

av_before <- data %>%
  filter(session==0) %>%
  mutate (group=0) %>%
  group_by(group, trial) %>%
  multi_boot_standard(col = "res")

av <- bind_rows(av_before,av_after)%>%
  mutate(type="both")

type_after <- data %>%
  filter(session==1) %>%
  group_by(group, type, trial) %>%
  multi_boot_standard(col = "res")

type_before <- data %>%
  filter(session==0) %>%
  mutate (group=0) %>%
  group_by(group, type, trial) %>%
  multi_boot_standard(col = "res")

typ <- bind_rows(type_before,type_after)
all <- bind_rows(av, typ)

```

Accuracy scores
```{r}
av_acc_after <- data %>%
  filter(session==1) %>%
  group_by(group, ID, trial) %>%
  summarise(accType = mean(res)) %>%
  mutate(subs=ifelse(trial == "same", -accType, accType))%>%
  select(-accType) %>%
  group_by(group, ID) %>%
  summarise(accType = sum(subs)) %>%
  group_by(group) %>%
  multi_boot_standard(col = "accType")
  
av_acc_before <- data %>%
  filter(session==0) %>%
  mutate (group=0) %>%
  group_by(group, ID, trial) %>%
  summarise(accType = mean(res)) %>%
  mutate(subs=ifelse(trial == "same", -accType, accType))%>%
  select(-accType) %>%
  group_by(group, ID) %>%
  summarise(accType = sum(subs)) %>%
  group_by(group) %>%
  multi_boot_standard(col = "accType")
  
av_acc <- bind_rows(av_acc_before, av_acc_after) %>%
  mutate(type="both")

type_acc_after <- data %>%
  filter(session==1) %>%
  group_by(group, ID, type, trial) %>%
  summarise(accType = mean(res)) %>%
  mutate(subs=ifelse(trial == "same", -accType, accType))%>%
  select(-accType) %>%
  group_by(group, ID, type) %>%
  summarise(accType = sum(subs)) %>%
  group_by(group, type) %>%
  multi_boot_standard(col = "accType")
  
type_acc_before <- data %>%
  filter(session==0) %>%
  mutate (group=0) %>%
  group_by(group, ID, type, trial) %>%
  summarise(accType = mean(res)) %>%
  mutate(subs=ifelse(trial == "same", -accType, accType))%>%
  select(-accType) %>%
  group_by(group, ID, type) %>%
  summarise(accType = sum(subs)) %>%
  group_by(group, type) %>%
  multi_boot_standard(col = "accType")
  
type_acc <- bind_rows(type_acc_before, type_acc_after)

all_acc <- bind_rows(av_acc, type_acc)


  
```

Plot

```{r}

all$type <- factor(all$type,
                    levels=c("guta","lita", "both"))


plot1  <- ggplot(all, aes(x = group, y= mean, col=type, shape=trial)) +
  geom_point(data=subset(all,type=='guta'), position = position_dodge(width = .2), size=2)+
  geom_point(data=subset(all,type=='lita'), position = position_dodge(width = .2), size=2)+
  geom_pointrange(data=subset(all,type=='both'),aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .03), size=0.5) +
  geom_line(data = subset(all, type=='guta' & trial=='diff' & group != '0' ), lty = 2)+
  geom_line(data = subset(all, type=='lita' & trial=='diff' & group != '0' ),  lty = 2)+
  geom_line(data = subset(all, type=='both' & trial=='diff' & group != '0' ))+
 xlab("group") +ylab("% different")+ theme_bw()+theme(strip.text = element_text(size=10), text = element_text(size=10)) + scale_y_continuous(limits=c(-0.02, 0.9))+ geom_hline(yintercept=0.5, linetype="dotted")+ geom_vline(xintercept = 0.5,lty=5 )
  #facet_grid(.~type)

plot1
```

```{r}
plot2  <- ggplot(all_acc, aes(x = group, y= mean, col=type)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = .1), size=0.3) + 
  geom_line(data = subset(all_acc, type=='guta' &  group != '0' ), lty = 2)+
  geom_line(data = subset(all_acc, type=='lita' & group != '0' ),  lty = 2)+
  geom_line(data = subset(all_acc, type=='both' & group != '0' ))+
 xlab("group") +ylab("% different")+ theme_bw()+theme(strip.text = element_text(size=10), text = element_text(size=10)) + scale_y_continuous(limits=c(-0.02, 0.9))+ geom_vline(xintercept = 0.5,lty=5 )
  #facet_grid(.~type)

plot2
```

Models

```{r}

#Learning
########

Gu <- data %>%
  filter(type=="guta", trial=="diff", session==1) 

mGu <- glmer(res ~ condition + (1 | ID) , data = Gu, family = binomial)
m0Gu <- glmer(res ~ 1+  (1 | ID) , data = Gu, family = binomial)  

#Estimates and SE
Summary(mGU)

#p-value (Liklihood ratio test)
anova(m0Gu, mGu, test="Chisq")


#Learning
##########

Li <- data %>%
  filter(type=="lita", trial=="diff", session == 1) 

mLi <- glmer(res ~ condition + (1 | ID) , data = Li, family = binomial)
m0Li <- glmer(res ~1+  (1 | ID) , data = Li, family = binomial) 


#Estimates and SE
Summary(mLi)

#p-value (Liklihood ratio test)
anova(m0Li, mLi, test="Chisq")

```

